### ISSUE TITLE
The bubble toolbar still shows up and allows you to edit text when the editor is set to readonly 

### ISSUE THREAD

**Issue by sferoze** [quilljs/quill#1052]
**Steps for Reproduction**

Initialize quill like so

```
@editor = new Quill(@find('.quill-editor'),
    placeholder: 'Enter Text...'
    modules:
      toolbar: toolbarOptions
      history:
        delay: 1000
        userOnly: true
        maxStack: 50 
      syntax: true
      formula: true
    theme: "bubble"
    readOnly: true
  )
```

And even though it is set to readOnly. You can still edit the contents. 

**Expected behavior**:

In readonly mode there should be no way to edit the document. Yet with the bubble theme, the toolbar still shows up and allows you to make edits. 

**Actual behavior**:

 With the bubble theme, the toolbar still shows up and allows you to make edits in read only mode. This should not happen.

**Platforms**:

Chrome

**Version**:

1.0.6
