### ISSUE TITLE
How to create custom embed format non selectable

### ISSUE THREAD

**Issue by emanuelbsilva** [quilljs/quill#1062]
Hi,

I would like to create a custom embed format which can be styled but it's text cannot be changed. My use case is pretty similar to the hashtag case. I want to have an external button that will add an hashtag to the current selected range on the editor. But after doing this i want the hashtag to behave as a "block" so that the user cannot go there and change its text.

The only way i could accomplish this was by saying that the format's node is contenteditable=false but i'm not sure i'm going the right way as i'm having some issues with this approach, mainly:
- If the hashtag is the last thing on the editor i cannot move past it (with arrows or cursor)
- Double clicking it to select should select the whole thing (and not individual words) (for styling)
- If the cursor is immediately behind the hashtag, pressing right and writing will write inside the hashtag

You can check a codepen i made while experimenting with this: http://codepen.io/emanuelbsilva/pen/Zpmmzv

If you guys can give me any tips on how can i accomplish this i would be glad.

**Comment by CapTec** [comment]
Could you please use stackoverflow for these types of questions. This area is specifically for issue/bug reporting. visit [http://stackoverflow.com/questions/tagged/quill](http://stackoverflow.com/questions/tagged/quill) for questions related to Quills usage.

**Comment by emanuelbsilva** [comment]
Sure,

But then we can say the issue is: "Lacking documentation on how to make custom embed formats".

**Comment by benbro** [comment]
You can make an element unselectable with CSS:
```css
.unselectable {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    -o-user-select: none;
    user-select: none;
}
```
http://codepen.io/anon/pen/vXPgvw
