### ISSUE TITLE
How to localize the link tooltip in the Snow theme

### ISSUE THREAD

**Issue by Retsam** [quilljs/quill#1192]
I'm trying to localize the English strings that show when you create or edit a link with the snow toolbar, but haven't gotten any traction. 

[This comment](https://github.com/quilljs/quill/issues/209#issuecomment-55049885) suggests that the entire template can be replaced, but I haven't found any documentation of that in the docs, nor do I know if the two year old comment is still applicable to v1.

**Version**: 1.0.0

**Comment by benbro** [comment]
The link tooltip string is defined [here](https://github.com/quilljs/quill/blob/f75ff2973f068c3db44f949915eb8a74faf162a8/assets/snow/tooltip.styl#L50).
You can override it:
```css
.ql-snow .ql-tooltip[data-mode="link"]::before {
    content: "Enter link:";
}
```
