### ISSUE TITLE
List layout bug in RTL mode

### ISSUE THREAD

**Issue by amitm02** [quilljs/quill#1498]
**Steps for Reproduction**

Create numbered list with text in RTL mode. see for example: [Quill example](https://jsfiddle.net/amitm02/vq8rhbx7/)

**Expected behavior**:
Wrap lines should start after the numbered index position, right below the first letter of the list item. see example of native css: [CSS example](https://jsfiddle.net/amitm02/908eyun9/)

**Actual behavior**:

English text works fine. But with Hebrew text (RTL mode), the wrap line text starts under the list item index number.  [Quill example](https://jsfiddle.net/amitm02/vq8rhbx7/)

**Platforms**:

Chrome & Safari

**Version**:
1.2.6

**Comment by benbro** [comment]
Need to decrease the window width to cause the lines to wrap and see the issue.

This fixes the indentation but it's not possible to style the ol element based on ql-direction-rtl class in the li child.
```css
.ql-editor ol, .ql-editor ul {
    padding-right: 1.5em;
}

.ql-editor li.ql-direction-rtl::before {
    margin-right: -1.5em;
}
```

@jhchen why do we need padding on ol element and negative margin on the li element?
Removing both doesn't seem to change the layout but fixes the rtl issue.

```css
.ql-editor ol, .ql-editor ul {
    padding-left: 1.5em;
}

.ql-editor li::before {
    margin-left: -1.5em;
}
```
