### ISSUE TITLE
When I set the toolbar to a fixed position, the editor gets the focus to scroll to the top

### ISSUE THREAD

**Issue by mengdu** [quilljs/quill#1690]
I need to do full screen processing for the editor, so the editor is highly automatic and the toolbar is fixed;But there's a problem with the fixed positioning toolbar, and every time you set the format editor to go back to the top, how do you solve this problem?

I checked the information, this is the editable div issue, but the editable div will automatically return to the top after the focus, but I still haven't solved it by restoring the cursor position.

## examples:

**html:***

```html
<div class="quill-editor">
  <div id="editor-container"></div>
</div>
```
**css:**
```css
.quill-editor{
    margin: 0 auto;
    width: 880px;
    min-height: 500px;
    margin-top: 100px;
  }
  .quill-editor .ql-editor{
    /*max-height: 400px;*/
  }
  .quill-editor .ql-toolbar.ql-snow,
  .quill-editor .ql-container.ql-snow{
    border: none;
  }
  .quill-editor .ql-toolbar{
    position: fixed;
    z-index: 100;
    background: #ccc;
    top: 0;
  }
```

**js:**

```js
var quill = new Quill('#editor-container', {
    debug: 'warn',
    modules: {
      formula: true,
      syntax: true,
        'history': {          // Enable with custom configurations
        'delay': 2500,
        'userOnly': true
      },
      toolbar: toolbarOptions,
    },
    placeholder: 'write here...',
    // bounds: '#editor-container',
    theme: 'snow' //bubble / snow
  });
```
