### ISSUE TITLE
Placeholder remains after clicking in editor

### ISSUE THREAD

**Issue by brianmcdonough** [quilljs/quill#1878]
Per the previous issue #1831 I can verify that ql-blank is not removed after clicking in the editor. 

It is removed after the user begins typing, but if consistent with other interfaces (medium) it would disappear after the click. 

Is there a way to override the behavior?

**Comment by benbro** [comment]
The placeholder can be removed on focus:
```css
.ql-editor.ql-blank:focus::before {
  content: '';
}
```
https://codepen.io/anon/pen/aEBmEp
