### ISSUE TITLE
Background color in the demo

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#199]
When changing the background color in the full example, it adds the background-color style but the authorship style overwrites it with:

``` css
.authorship .author-galadriel {
    background-color: white;
}
```

http://quilljs.com/examples/
