### ISSUE TITLE
How to set all images in editor with inline style `display:block`

### ISSUE THREAD

**Issue by ke1vin666** [quilljs/quill#2218]
How to set all images that inserted or pasted to editor with inline style `display:block`?
I don't want to use external css rule to control it, any methods ?

**Comment by DarnellSh** [comment]
@ke1vin666 
```css
.ql-image {
      display: block
}
```

in your own css.
