### ISSUE TITLE
quill图片显示的大小怎么控制

### ISSUE THREAD

**Issue by SkyliHaiLan** [quilljs/quill#2230]
富文本编辑器状态是 editor.enable(false),是只读状态，当我上传一张很大的图片。屏幕上都超出去了，我想固定控制图片的宽度，求解？
![image](https://user-images.githubusercontent.com/31440880/43812234-d65de2d0-9af2-11e8-8bd7-fe8d032406b1.png)

**Comment by 1c7** [comment]
我不是 quill 专家，不过根据你的描述和我觉得有两种方法

1. 直接 css 控制
```css
.editor{
   img{
     width: 100%;
  }
}
```
2. 如果希望用户可以拉大缩小图片，我记得 quill 有几个 module 可以做到。

另外。建议能用英文就用英文。像这样的库里用中文大大减少了别人回复你的可能性
