### ISSUE TITLE
Best way to put quill editor with toolbar to a container with limited sizes

### ISSUE THREAD

**Issue by anna-kartynnik** [quilljs/quill#2501]
First of all, thank you for so cool rich text editor!
I have a container (`div`) with specific width and height and I want to put quill editor in that container. My problem is that quill's `div` doesn't fill its parent `div`, its height is equal to the parent's height + toolbar's height and the content goes beyond the boundaries of the parent container. My first thought was to change the container's height to something like `calc(200px - 42px) /* where 42px is a toolbar's height */` but if we make the parent container narrower, we'll have 2 rows of toolbar controls, so the toolbar's height will be different. Right now I'm thinking about adding javascript code for getting a real current height of toolbar and about adjusting the parent container's height respectively. Before doing this I wanted to ask if there are any other options to have quill editor that fills its parent completely, or any other options to make it work with css only.

**Steps for Reproduction**

1. Visit https://jsfiddle.net/k5s7d3fx/
2. Have a look at the containers there: I created two `div`s with identical heights and different widths. Red borders are added to make parent containers boundaries easily visible. As you can see, quill content goes outside the parent container border.

**Expected behavior**:

Quill's `div` fills a parent `div`.

**Actual behavior**:

Quill's `div` has height equal to parent height + toolbar height and its content goes beyond the parent container's boundaries.

**Platforms**:

Any browser but Chrome Version 71.0.3578.98 (Official Build) (64-bit) in particular
macOS Mojave Version 10.14.2

**Version**:

1.3.6

**Comment by benbro** [comment]
This is a general CSS question and not specific to Quill.
Please ask questions on StackOverflow.
You can try this:
https://jsfiddle.net/pykm29bo/3/

```css
#editor-container1 {
  width: 200px;
  height: 200px;
  border: 1px solid red;
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  align-items: stretch;
}

#editor1 {
  overflow-y: hidden;
}
```
