### ISSUE TITLE
ql-editor css style

### ISSUE THREAD

**Issue by ghost** [quilljs/quill#2615]
I am using the quill bubble-style in my project and I noticed the following style:

```css
.ql-editor > * {
  cursor: text;
}
```

Is there any particular reason for this explicit style? The reason I ask is because this prevents one from wrapping the editor inside another element and set `cursor: pointer`:

```html
<div style="cursor: pointer; padding: 5px">
   <!-- quill -->
      <div class="ql-editor">
          <p> ... </p>
      </div>
   <!-- /quill -->
</div>
```

If there is no explicit need for this style, would it be an option to remove it?

**Comment by TanguyP** [comment]
I'm not a Quill contributor, and I'm coming a bit late, but I think this will do the trick to apply your custom style:

HTML:
```html
<div class="quill-wrapper">
   <!-- quill -->
      <div class="ql-editor">
          <p> ... </p>
      </div>
   <!-- /quill -->
</div>
```

CSS:
```css
.quill-wrapper .ql-editor > * {
  cursor: pointer;
  padding: 5px;
}
```
