### ISSUE TITLE
The font-size of list marker don't sync with text font-size

### ISSUE THREAD

**Issue by MatteoGauthier** [quilljs/quill#3721]
The font-size of the marker element (bullets, ordered) is not synced with the paragraph styling

https://user-images.githubusercontent.com/32040951/211772089-f52d6279-5016-4278-8e66-41c985811bb0.mov

**Comment by yashnerkar** [comment]
can i work  on this?

**Comment by minteliuwm** [comment]
I'm experiencing this problem too, is there a solution?

**Comment by buecherlstefan** [comment]
Is there any solution already? Same with color

**Comment by 17biubiu** [comment]
same problem！！

**Comment by cattermo** [comment]
There is a somewhat hacky solution to fix this, the sad thing is that it requires one rule per font-size and color.
Here is and example to fix font-sizes. If you have access to sass code it can be done with a pretty neatly with this mixin. 

```scss
$editor-font-sizes: 12px, 14px, 16px, 18px;

@mixin fontsizeFromChild ($element, $value) {
  #{$element}:has([style*='font-size: #{$value}']) {
    font-size: $value;
  }
}

@mixin addFontsizeForUlOl () {
  @each $font-size in $editor-font-sizes {
    @include fontsizeFromChild(ul, $font-size);
  }
  @each $font-size in $editor-font-sizes {
    @include fontsizeFromChild(ol, $font-size);
  }
}
```

```scss
// Add to editor
.ql-editor {
	@include addFontsizeForUlOl();
}
// Also add to wherever the text is displayed
.my-preview-thing {
	@include addFontsizeForUlOl();
}
```
Color could be fixed in a similar way, just add a mixin to set the color property instead and an array with all supported colors.
