### ISSUE TITLE
Documention to show customizing toolbar / using Parchment in v1.0.0

### ISSUE THREAD

**Issue by george-norris-salesforce** [quilljs/quill#828]
Looking for examples / documentation on customizing toolbar / using Parchment in v1.0.0

**Comment by jhchen** [comment]
Can you elaborate on what you are trying to do? Not saying they are perfect but both the [toolbar](http://beta.quilljs.com/docs/modules/toolbar/) and [Parchment](https://github.com/quilljs/parchment) already have documentation and it would be helpful to know the specific gaps.

**Comment by george-norris-salesforce** [comment]
Didn't see the Parchment  docs on GH. 
Trying to create custom block / inline elements (with buttons in toolbar).

**Comment by alexkrolick** [comment]
I was just dealing with this so here's a start on the documentation:

Say you're adding a custom save icon to your existing toolbar with a header dropdown:

```js
modules: {
    toolbar: [ [{ 'header': [1, 2, false] }], ['save'] ],
     ...
}
```

would add an icon .ql-save to the toolbar which you would customize in your CSS somewhere:

```css
.ql-save {
    background: url("/assets/save.svg") no-repeat scroll 0% 0% transparent !important
    width: 18px !important
    border-radius: 0px
    height: 15px !important
    text-align: center
    background-position: center
}
```
Then add a listener:
```js
document.querySelector( '.ql-save').addEventListener('click', saveCallback);
```

To hook up the button to a custom format you need to register it in the formats module. For example if you are adding a thing called `title` that is really just an `h1` tag, you could do this and add a `title` button to the toolbar and customize as above:

```js
    formats: [{ name: "title", tag: "H1", prepare: "heading", type: "line" }]
```

**Not sure exactly what listeners would be needed, if any, to get this to automatically create tags around the selection when you click the icon** @jhchen
