### ISSUE TITLE
More prominent hover/active button style

### ISSUE THREAD

**Issue by benbro** [quilljs/quill#837]
In my opinion the blue color when a button is hover or active is not noticeable enough.
I've added border around the buttons on hover/active and background-color when active.
Please try hover and active in the following example:

http://codepen.io/anon/pen/jAvOKG

The only thing missing is to collapse the border when two neighboring buttons are active so we don't get double border. Not sure how.

Feel free to close this if you don't like the style.

**Version**: [version]
1.0.0-beta.9

**Comment by benbro** [comment]
Borders can be collapsed with (and the same for hover/hover, hover/active and active/hover)
```css
.ql-active + .ql-active,
.ql-active + .ql-selected,
.ql-selected + .ql-active,
.ql-selected + .ql-selected {
  border-left-color: transparent !important;
}
```
