### ISSUE TITLE
Document how to add new toolbar svg icons without creating a toolbar in HTML

### ISSUE THREAD

**Issue by kheraud** [quilljs/quill#885]
I am trying to add the undo/redo feature for my quill editor :
```
var toolbarOptions = [
  ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
  ['undo'],
  ['redo'],
];
var quill = new Quill('#editor', {
  theme: 'snow',
  placeholder: 'Compose an epic message...',
  readOnly: false,
  modules: {
    history: {
      delay: 2000,
      userOnly: true
    },
    toolbar: {
      container: toolbarOptions,
      handlers: {
        undo: function(value) {
          this.quill.history.undo();
        },
        redo: function(value) {
          this.quill.history.redo();
        }
      }
    }
  }
});

```
The undo/redo buttons work well but they are not rendered (blank buttons).

I  can see that svg icons for redo and undo are located in the `assets/icons` folder but I can't figure out how to have them rendered in the toolbar.
It seems that all is wired in `ui/icons.js` but I would like to add this through config options. Is there a way to do that ? I can't find anything about that in the documentation (btw, congratulation for the documentation, it has been updated a lot these last 2 months 👍)

**Comment by jhchen** [comment]
The icons created in batches so they maintain a consistent style and some are not being used by the project or included in builds. I decided to put all of them in `assets/icons/` to make them available in case they are useful. 

The way to use them would be to create your own toolbar in HTML and pass that into the [container option](http://quilljs.com/docs/modules/toolbar/#container) so there's no way to do what you are asking at the moment. If you'd like to add this ability, I'd be happy to take a look at a PR. I think what you would need to do is add the icons to ui/icon.js and the handlers to modules/toolbar.js.

**Comment by alexkrolick** [comment]
Quill creates buttons with .ql-* classes for every registered style in the config. You can override the blank buttons by targeting those classes with CSS as below (for an attachment icon):
```css
.ql-attachment {
  background: no-repeat scroll 50% 50% transparent !important;
  background-image: url("attachment.svg") !important;
  text-align: center;
}
.ql-attachment:hover {
  background-image: url("attachment-hover.svg") !important
}
```
